stages:
  - pages

pages:
  stage: pages
  image: grauwoelfchen/rust:stable
  before_script:
    - make setup
    - make clean
  script:
    - make publish
  artifacts:
    paths:
      - public
  only:
    - master
