[website]
title = "Grauwoelfchen's Forge"
description = """
"""
lang = "en" # HTML attribute. set language_code
# url = "http://127.0.0.1:3000"
url = "https://forge.grauwoelfchen.net"
include = [
  "blog/post/*.rst"
]
license = "CC-BY-NC-SA-4.0"
# authors = [
#  "Yasha <yasuhiro.asaka@grauwoelfchen.net>",
# ]

[build]
target-dir = "dst"

[[website.metadata.authors]]
name = "Yasha"
nick = "grauwoelfchen"
# TODO
bio = """
<p>Hoi Zäme!<br/>
I'm a programmer who enjoys writing software on Gentoo/Funtoo or OpenBSD by day and reading books in quiet by night.<br/>
I love greenery and grow vegetables.<br/>
<br/>
I'm currently learning to draw and crochet/knit ;)<br/>
<br/>
<a href="https://grauwoelfchen.net/about.html">https://grauwoelfchen.net</a></p>
--
<br />
<p>Mastodon:<br/><a href="https://fosstodon.org/@grauwoelfchen">@grauwoelfchen@fosstodon.org</a></p>
<p>Pixelfed:<br/><a href="https://pixelfed.social/grauwoelfchen">@grauwoelfchen@pixelfed.social</a></p>
<br />
<span style="font-size: 0.76em">Copyright (C) 2017-2025 Yasha</span>
"""
email = ""
avatar = "https://www.gravatar.com/avatar/caf84d2962cbae495fe70b1b40872637?s=40"
